<?php

/**
 * BasePollAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quote_id
 * @property integer $source_id
 * @property integer $user_id
 * @property string $token
 * @property Quote $Quote
 * @property Source $Source
 * @property sfGuardUser $User
 * 
 * @method integer     getQuoteId()   Returns the current record's "quote_id" value
 * @method integer     getSourceId()  Returns the current record's "source_id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method string      getToken()     Returns the current record's "token" value
 * @method Quote       getQuote()     Returns the current record's "Quote" value
 * @method Source      getSource()    Returns the current record's "Source" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method PollAnswer  setQuoteId()   Sets the current record's "quote_id" value
 * @method PollAnswer  setSourceId()  Sets the current record's "source_id" value
 * @method PollAnswer  setUserId()    Sets the current record's "user_id" value
 * @method PollAnswer  setToken()     Sets the current record's "token" value
 * @method PollAnswer  setQuote()     Sets the current record's "Quote" value
 * @method PollAnswer  setSource()    Sets the current record's "Source" value
 * @method PollAnswer  setUser()      Sets the current record's "User" value
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
abstract class BasePollAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_answer');
        $this->hasColumn('quote_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('source_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('token', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quote', array(
             'local' => 'quote_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Source', array(
             'local' => 'source_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}