<?php

/**
 * BaseVoucher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $offer_id
 * @property integer $type
 * @property float $value
 * @property timestamp $expired_at
 * @property integer $max_uses
 * @property integer $uses_count
 * @property boolean $active
 * @property sfGuardUser $User
 * @property Offer $Offer
 * 
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method integer     getOfferId()    Returns the current record's "offer_id" value
 * @method integer     getType()       Returns the current record's "type" value
 * @method float       getValue()      Returns the current record's "value" value
 * @method timestamp   getExpiredAt()  Returns the current record's "expired_at" value
 * @method integer     getMaxUses()    Returns the current record's "max_uses" value
 * @method integer     getUsesCount()  Returns the current record's "uses_count" value
 * @method boolean     getActive()     Returns the current record's "active" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method Offer       getOffer()      Returns the current record's "Offer" value
 * @method Voucher     setUserId()     Sets the current record's "user_id" value
 * @method Voucher     setOfferId()    Sets the current record's "offer_id" value
 * @method Voucher     setType()       Sets the current record's "type" value
 * @method Voucher     setValue()      Sets the current record's "value" value
 * @method Voucher     setExpiredAt()  Sets the current record's "expired_at" value
 * @method Voucher     setMaxUses()    Sets the current record's "max_uses" value
 * @method Voucher     setUsesCount()  Sets the current record's "uses_count" value
 * @method Voucher     setActive()     Sets the current record's "active" value
 * @method Voucher     setUser()       Sets the current record's "User" value
 * @method Voucher     setOffer()      Sets the current record's "Offer" value
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
abstract class BaseVoucher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('voucher');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('offer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('expired_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('max_uses', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('uses_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Offer', array(
             'local' => 'offer_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}