<?php

/**
 * BaseInvitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property string $email
 * @property integer $group_id
 * @property Event $Event
 * @property AuthGroup $Group
 * 
 * @method integer    getEventId()  Returns the current record's "event_id" value
 * @method string     getEmail()    Returns the current record's "email" value
 * @method integer    getGroupId()  Returns the current record's "group_id" value
 * @method Event      getEvent()    Returns the current record's "Event" value
 * @method AuthGroup  getGroup()    Returns the current record's "Group" value
 * @method Invitation setEventId()  Sets the current record's "event_id" value
 * @method Invitation setEmail()    Sets the current record's "email" value
 * @method Invitation setGroupId()  Sets the current record's "group_id" value
 * @method Invitation setEvent()    Sets the current record's "Event" value
 * @method Invitation setGroup()    Sets the current record's "Group" value
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseInvitation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invitation');
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('AuthGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}