<?php

/**
 * BasePollChoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quote_id
 * @property string $choice_value
 * @property integer $votes_count
 * @property Quote $Quote
 * 
 * @method integer    getQuoteId()      Returns the current record's "quote_id" value
 * @method string     getChoiceValue()  Returns the current record's "choice_value" value
 * @method integer    getVotesCount()   Returns the current record's "votes_count" value
 * @method Quote      getQuote()        Returns the current record's "Quote" value
 * @method PollChoice setQuoteId()      Sets the current record's "quote_id" value
 * @method PollChoice setChoiceValue()  Sets the current record's "choice_value" value
 * @method PollChoice setVotesCount()   Sets the current record's "votes_count" value
 * @method PollChoice setQuote()        Sets the current record's "Quote" value
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
abstract class BasePollChoice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_choice');
        $this->hasColumn('quote_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('choice_value', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('votes_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quote', array(
             'local' => 'quote_id',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}