<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Subscription $Subscription
 * @property Auth $Auth
 * @property Doctrine_Collection $Quote
 * @property Doctrine_Collection $Answer
 * @property Doctrine_Collection $PollAnswer
 * @property Doctrine_Collection $Vote
 * @property Doctrine_Collection $StatUser
 * 
 * @method Subscription        getSubscription() Returns the current record's "Subscription" value
 * @method Auth                getAuth()         Returns the current record's "Auth" value
 * @method Doctrine_Collection getQuote()        Returns the current record's "Quote" collection
 * @method Doctrine_Collection getAnswer()       Returns the current record's "Answer" collection
 * @method Doctrine_Collection getPollAnswer()   Returns the current record's "PollAnswer" collection
 * @method Doctrine_Collection getVote()         Returns the current record's "Vote" collection
 * @method Doctrine_Collection getStatUser()     Returns the current record's "StatUser" collection
 * @method sfGuardUser         setSubscription() Sets the current record's "Subscription" value
 * @method sfGuardUser         setAuth()         Sets the current record's "Auth" value
 * @method sfGuardUser         setQuote()        Sets the current record's "Quote" collection
 * @method sfGuardUser         setAnswer()       Sets the current record's "Answer" collection
 * @method sfGuardUser         setPollAnswer()   Sets the current record's "PollAnswer" collection
 * @method sfGuardUser         setVote()         Sets the current record's "Vote" collection
 * @method sfGuardUser         setStatUser()     Sets the current record's "StatUser" collection
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subscription', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('Auth', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Quote', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Answer', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('PollAnswer', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Vote', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('StatUser', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}