<?php

/**
 * BaseSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Quote
 * @property Doctrine_Collection $PollAnswer
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method Doctrine_Collection getQuote()      Returns the current record's "Quote" collection
 * @method Doctrine_Collection getPollAnswer() Returns the current record's "PollAnswer" collection
 * @method Source              setTitle()      Sets the current record's "title" value
 * @method Source              setQuote()      Sets the current record's "Quote" collection
 * @method Source              setPollAnswer() Sets the current record's "PollAnswer" collection
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('source');
        $this->hasColumn('title', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Quote', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $this->hasMany('PollAnswer', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'name' => 'small_title',
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}