<?php

/**
 * BaseAuthGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $short
 * @property Doctrine_Collection $Auth
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method string              getShort() Returns the current record's "short" value
 * @method Doctrine_Collection getAuth()  Returns the current record's "Auth" collection
 * @method AuthGroup           setName()  Sets the current record's "name" value
 * @method AuthGroup           setShort() Sets the current record's "short" value
 * @method AuthGroup           setAuth()  Sets the current record's "Auth" collection
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
abstract class BaseAuthGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auth_group');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('short', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Auth', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
}