<?php

/**
 * BaseStatUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $total_quotes
 * @property integer $validated_quotes
 * @property integer $total_votes
 * @property integer $votes_for_quotes
 * @property integer $answered_questions
 * @property integer $events_used
 * @property integer $walls_used
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()             Returns the current record's "user_id" value
 * @method integer     getTotalQuotes()        Returns the current record's "total_quotes" value
 * @method integer     getValidatedQuotes()    Returns the current record's "validated_quotes" value
 * @method integer     getTotalVotes()         Returns the current record's "total_votes" value
 * @method integer     getVotesForQuotes()     Returns the current record's "votes_for_quotes" value
 * @method integer     getAnsweredQuestions()  Returns the current record's "answered_questions" value
 * @method integer     getEventsUsed()         Returns the current record's "events_used" value
 * @method integer     getWallsUsed()          Returns the current record's "walls_used" value
 * @method sfGuardUser getUser()               Returns the current record's "User" value
 * @method StatUser    setUserId()             Sets the current record's "user_id" value
 * @method StatUser    setTotalQuotes()        Sets the current record's "total_quotes" value
 * @method StatUser    setValidatedQuotes()    Sets the current record's "validated_quotes" value
 * @method StatUser    setTotalVotes()         Sets the current record's "total_votes" value
 * @method StatUser    setVotesForQuotes()     Sets the current record's "votes_for_quotes" value
 * @method StatUser    setAnsweredQuestions()  Sets the current record's "answered_questions" value
 * @method StatUser    setEventsUsed()         Sets the current record's "events_used" value
 * @method StatUser    setWallsUsed()          Sets the current record's "walls_used" value
 * @method StatUser    setUser()               Sets the current record's "User" value
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseStatUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stat_user');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total_quotes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('validated_quotes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('total_votes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('votes_for_quotes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('answered_questions', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('events_used', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('walls_used', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}