#### WALL

wall:
  url: /event/:event/walls
  param: { module: wall, action: index }
  requirements: { sf_method: get }
  
wall_new:
  url: /event/:event/walls/new
  param: { module: wall, action: new }
  requirements: { sf_method: get }

wall_create:
  url: /event/:event/walls/create
  param: { module: wall, action: create }
  requirements: { sf_method: post }

wall_edit:
  url: /event/:event/walls/edit/:id
  param: { module: wall, action: edit }
  requirements: { sf_method: get }

wall_update:
  url: /event/:event/walls/update/:id
  param: { module: wall, action: update }
  requirements: { sf_method: put }

wall_delete:
  url: /event/:event/walls/delete/:id
  param: { module: wall, action: delete }
  requirements: { sf_method: delete }

event:
  class: sfDoctrineRouteCollection
  options:
    model:                event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }