<?php

/**
 * Quote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
class Quote extends BaseQuote
{
  /**
   * Alias to setValidated
   *
   * @return void
   * @author Clément JOBEILI
   */
  public function validate()
  {
    $this->setIsValidated(true);
    $this->save();
  }
  
  /**
   * Alias to getIsValidated
   *
   * @return boolean
   * @author Clément JOBEILI
   */
  public function isValidated()
  {
    return $this->getIsValidated();
  }
}
