<?php

/**
 * Source
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
class Source extends BaseSource
{
  
  
  public static $WEB        = 1;
  public static $SMARTPHONE = 2;
  public static $SMS        = 3;
  public static $TWITTER    = 4;
  public static $WIDGET     = 5;
  public static $EMAIL      = 6;
  
  public static function find($request, $force = "")
  {
    return 1; // To Change (with test on the user agent ());
  }
}
