<?php

/**
 * Wall
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    balloon
 * @subpackage model
 * @author     Clément JOBEILI <clement.jobeili@gmail.com>
 * @version    SVN: $Id$
 */
class Wall extends BaseWall
{

  public function isAvailable()
  {
    return ($this->getStart() < $this->getRealStartDate() && $this->getRealStartDate() < $this->getStop());
  }

  public function getAuth()
  {
    return $this->getEvent()->getAuth();
  }
  
  public function isModerated()
  {
    return ($this->getIsModerated());
  }
  
  /**
   * Check if the wall support a action with his offer
   *
   * @param string $action 
   * @return boolean
   * @author Clément JOBEILI
   */
  function supports($action)
  {
    $actions = WallSupport::getActions();
    if(!isset($actions[$action])){
      throw new Exception(sprintf('The action "%s" does not exists', $action));
    }
    
    $offer = Doctrine::getTable('Subscription')->findOneByWall($this);

    if(!$offer){
      return false;
    }

    $offer = $offer->getOffer();
    
    return ($offer->get($actions[$action]));
  }
}
