# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# sfDoctrineGuard
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_register:
  url: /signup/:plan
  param: { module: sfGuardRegister, action: index, plan: "" }

sf_guard_forgot_password:
  url: /user/lostpassword
  param: { module: sfGuardForgotPassword, action: index }
  
plans:
  url: /plans
  param: { module: sfGuardRegister, action: plans }

user_edit:
  url: /me
  param: { module: user, action: edit }
# dashboard

dashboard:
  url: /dashboard
  param: { module: home, action: dashboard }

confirm_mail:
  url: /user/confirm/token/:token
  param: { module: sfGuardRegister, action: confirm, token: "" }

# Laisser a la fin.
event:
  url: /:short
  param: { module: event, action: show }

event_edit:
  url: /:short/edit
  param: { module: event, action: edit }
  
invitation:
  url: /:event/invitation
  param: { module: invitation, action: index }

invitation_create:
  url: /:event/invitation/create
  param: { module: invitation, action: create }

wall:
  url: /:event/:wall
  param: { module: wall, action: show }

wall_edit:
  url: /:event/:wall/edit
  param: { module: wall, action: edit }
  
quote_create:
  url: /:event/:wall/quote/create
  param: { module: quote, action: create }
  requirements: { sf_method: post }

quote_vote:
  url: /:event/:wall/quote/:quote/vote
  param: { module: quote, action: vote }

quote_validate:
  url: /:event/:wall/quote/:quote/validate
  param: { module: quote, action: validate }

quote_remove:
  url: /:event/:wall/quote/:quote/delete
  param: { module: quote, action: delete }

quote_edit:
  url: /:event/:wall/quote/:quote/edit
  param: { module: quote, action: edit }

quote_answer:
  url: /:event/:wall/quote/:quote/answer
  param: { module: quote, action: answer }

quote_favorite:
  url: /:event/:wall/quote/:quote/fav
  param: { module: quote, action: favorite }

answer_create:
  url: /:event/:wall/quote/:quote/answer/create
  param: { module: answer, action: create }
  requirements: { sf_method: post }

answer_delete:
  url: /:event/:wall/quote/:quote/answer/:answer/delete
  param: { module: answer, action: delete }
  requirements: { sf_method: delete }

answer_edit:
  url: /:event/:wall/quote/:quote/answer/:answer/edit
  param: { module: answer, action: edit }

choice_vote:
  url: /:event/:wall/quote/:quote/choice/vote
  param: { module: choice, action: vote }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
