generator:
  class: sfDoctrineGenerator
  param:
    model_class:           event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, =short, logo, wall_count]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
